from numpy import *
from matplotlib.pyplot import *
n = linspace(0,6,7)
n5 = linspace(0,4,5)
n3 = linspace(0,2,3)
h = array([10,-8,6])
x = array([7,-6,0,12,8])
y = convolve(x,h,mode = 'full')
print(y)
subplot(3,1,1)
stem(n3,h)
ylabel('h(n)')
subplot(3,1,2)
stem(n5,x)
ylabel('x(n)')
subplot(3,1,3)
stem(n,y)
ylabel('y(n)')
show()